# Machine Learning-Based Prediction of 30-Day Hospital Readmission in Diabetic Patients

## Import Libraries

In [1]:
import joblib
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import SMOTE

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    f1_score
)

In [2]:
df = pd.read_csv("./data/day-28.csv")

In [3]:
X = df.drop(columns=['readmitted_binary'])
y = df['readmitted_binary']

## Training ML models

In [4]:
# Train Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y # ensures the training and testing sets retain the same proportion of classes
)

In [5]:
# Preprocessing pipeline

preprocessor = joblib.load("./data/preprocessing_pipeline.pkl")

### Logistic Regression Pipeline

In [6]:
# Logistic Regression Pipeline

log_model = Pipeline(steps=[
  ('preprocessor', preprocessor),
  ('classifier', LogisticRegression(
    class_weight='balanced',   # assigning higher importance to the minority class
    max_iter=1000,
    random_state=42
  ))
])

log_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['age', 'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'A1Cresult', 'change',
       'diabetesMed', 'total_diabetes_drugs', 'insulin_flag', 'oral_med_flag',
       'is_polypharmacy'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['race', 'gender',
                                                   'admission_type',
                                                   'discharge_disposition',
                                                   'admission_source',
                                                   'medical_specialty',
                                                   'diag_1', 'diag_2',
                                                   'diag_3'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [7]:
# Evaluate Logistic Regression

y_pred_log = log_model.predict(X_test)
y_prob_log = log_model.predict_proba(X_test)[:, 1]


print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_prob_log))

Confusion Matrix:
 [[12369  5713]
 [  967  1304]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.68      0.79     18082
           1       0.19      0.57      0.28      2271

    accuracy                           0.67     20353
   macro avg       0.56      0.63      0.53     20353
weighted avg       0.84      0.67      0.73     20353


ROC-AUC Score: 0.6804988780744464


### Random Forest Pipeline

In [16]:
# Random Forest Model

rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=100,   # number of decision trees
        class_weight='balanced',
        random_state=42
    ))
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['age', 'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'A1Cresult', 'change',
       'diabetesMed', 'total_diabetes_drugs', 'insulin_flag', 'oral_med_flag',
       'is_polypharmacy'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['race', 'gender',
                                                   'admission_type',
                                                   'discharge_disposition',
                                                   'admission_source',
                                                   'medical_specialty',
                                                   'diag_1', 'diag_2',
                                                   'diag_3'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        random_state=42))])

In [17]:
# Evaluate Logistic Regression

y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_prob_rf))

Confusion Matrix:
 [[18074     8]
 [ 2254    17]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94     18082
           1       0.68      0.01      0.01      2271

    accuracy                           0.89     20353
   macro avg       0.78      0.50      0.48     20353
weighted avg       0.87      0.89      0.84     20353


ROC-AUC Score: 0.6622833619007807


### Decision Tree Pipeline

In [8]:
# Decision Tree

dt_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(
        class_weight='balanced',
        random_state=42
    ))
])

dt_model.fit(X_train, y_train)


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['age', 'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'A1Cresult', 'change',
       'diabetesMed', 'total_diabetes_drugs', 'insulin_flag', 'oral_med_flag',
       'is_polypharmacy'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['race', 'gender',
                                                   'admission_type',
                                                   'discharge_disposition',
                                                   'admission_source',
                                                   'medical_specialty',
                                                   'diag_1', 'diag_2',
                                                   'diag_3'])])),
                ('classifier',
                 DecisionTreeClassifier(class_weight='balanced',
                                        random_state=42))])

In [9]:
y_pred_dt = dt_model.predict(X_test)
y_prob_dt = dt_model.predict_proba(X_test)[:, 1]

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_prob_dt))

Confusion Matrix:
 [[15909  2173]
 [ 1869   402]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.88      0.89     18082
           1       0.16      0.18      0.17      2271

    accuracy                           0.80     20353
   macro avg       0.53      0.53      0.53     20353
weighted avg       0.81      0.80      0.81     20353


ROC-AUC Score: 0.5284198858071633


### XGBoost

In [10]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline

In [11]:
# Calculate Class Imbalance Weight

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

scale_pos_weight = neg / pos
print(scale_pos_weight)

7.959938366718028


In [12]:
# Creating XGBoost Pipeline

xgb_model = Pipeline(steps=[
  ('preprocessor', preprocessor),
  ('classifier', XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    eval_metric='logloss',
    random_state=42
  ))
])

In [13]:
xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['age', 'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'A1Cresult', 'change',
       'diabetesMed', 'total_diabetes_drugs', 'insulin_flag', 'oral_med_flag',
       'is_poly...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [14]:
y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)[:,1]

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_prob_xgb))

Confusion Matrix:
 [[12446  5636]
 [  941  1330]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.69      0.79     18082
           1       0.19      0.59      0.29      2271

    accuracy                           0.68     20353
   macro avg       0.56      0.64      0.54     20353
weighted avg       0.85      0.68      0.73     20353


ROC-AUC Score: 0.6927396432836351


## Model Comparison

In [18]:
comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest", "Decision Tree", "XGBoost"],
    "ROC-AUC": [
        roc_auc_score(y_test, y_prob_log),
        roc_auc_score(y_test, y_prob_rf),
        roc_auc_score(y_test, y_prob_dt),
        roc_auc_score(y_test, y_prob_xgb)
    ]
})

comparison

Model   ROC-AUC
0  Logistic Regression  0.680499
1        Random Forest  0.662283
2        Decision Tree  0.528420
3              XGBoost  0.692740

## Improving Logistic Regression Model

### Using Threshold

In [19]:
# Using Threshold

y_pred_log = log_model.predict(X_test)
y_prob_log = log_model.predict_proba(X_test)[:, 1]

threshold = 0.3
y_pred_log_thresh = (y_prob_log >= threshold).astype(int)


print("Threshold Used:", threshold)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_log_thresh))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log_thresh))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_prob_log))

Threshold Used: 0.3

Confusion Matrix:
 [[ 1186 16896]
 [   30  2241]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.07      0.12     18082
           1       0.12      0.99      0.21      2271

    accuracy                           0.17     20353
   macro avg       0.55      0.53      0.17     20353
weighted avg       0.88      0.17      0.13     20353


ROC-AUC Score: 0.6804988780744464


In [20]:
# Find Best Threshold Automatically

thresholds = np.arange(0.1, 0.9, 0.05)
f1_scores = []

for t in thresholds:
    y_pred_temp = (y_prob_log >= t).astype(int)
    f1 = f1_score(y_test, y_pred_temp)
    f1_scores.append(f1)

best_threshold = thresholds[np.argmax(f1_scores)]
print("Best Threshold:", best_threshold)
print("Best F1 Score:", max(f1_scores))

Best Threshold: 0.5000000000000001
Best F1 Score: 0.28079242032730406


In [24]:
# Best thrushold is as same as default

### Using SMOTE

In [21]:
from imblearn.pipeline import Pipeline

In [22]:
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression

log_model_sm = Pipeline(steps=[
    ('preprocessor', preprocessor),   # encode + scale FIRST
    ('smote', SMOTE(random_state=42)), # THEN balance data
    ('classifier', LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

In [23]:
log_model_sm.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['age', 'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'A1Cresult', 'change',
       'diabetesMed', 'total_diabetes_drugs', 'insulin_flag', 'oral_med_flag',
       'is_polypharmacy'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['race', 'gender',
                                                   'admission_type',
                                                   'discharge_disposition',
                                                   'admission_source',
                                                   'medical_specialty',
                                                   'diag_1', 'diag_2',
                                                   'diag_3'])])),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [25]:
y_pred_log_sm = log_model_sm.predict(X_test)
y_prob_log_sm = log_model_sm.predict_proba(X_test)[:,1]

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log_sm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log_sm))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_prob_log_sm))

Confusion Matrix:
 [[11891  6191]
 [ 1027  1244]]

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.66      0.77     18082
           1       0.17      0.55      0.26      2271

    accuracy                           0.65     20353
   macro avg       0.54      0.60      0.51     20353
weighted avg       0.84      0.65      0.71     20353


ROC-AUC Score: 0.652601600488133


In [26]:
# SMOTE does not work very well here

## Saving Final Model (Logistic Regression)

In [27]:
joblib.dump(log_model, "./model/final_model.pkl")

['./model/final_model.pkl']